version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build:
      context: .
    container_name: nestjs-backend
    restart: always
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
    ports:
      - "5091:5091"
    depends_on:
      - postgres
    networks:
      - backend-network
    volumes:
      - ./:/app
    command: npm run start:dev

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data: